### ISSUE TITLE
Unisolated environment

### ISSUE THREAD

**Issue by radiumatic** [aleskxyz/reality-ezpz#122]
Hi,

First of all, this works great, bravo. :)

But on low-tier servers, considering that many might want to run other services too, docker *is* bit of an overhead. (100MB of additional RAM usage compared to running x-ui + a bunch of other things) 
It would be nice to have the option to disable it. (the only changes in script should be prefix commands of `docker exec`?)

Thanks in advance.

**Comment by aleskxyz** [comment]
Hi,

Thank you for your kind words and feedback. 

One of the design goals of this script is to make as few changes as possible to the OS by using containers and Docker. I can say that this script has the lowest resource footprint compared to other methods that use a GUI for management, by sacrificing a bit of overhead for Docker instead of GBs of RAM for a web interface.

This approach also enables us to make this script portable across different OSes. Additionally, you can copy the entire /opt/reality-ezpz directory to another server and run exactly the same configuration on other servers. This is helpful in case you want to migrate to a new server if the IP is blacklisted.

If you look at the code of the Telegram bot, you will see that the bot also executes the entire script with each call. If you want to create an installer like other scripts that use the underlying OS, then you need to accommodate different OSes, and you cannot backup and migrate configurations easily.

I can provide an over-the-air update by changing the version of the Docker image in the script, and users might not even notice the upgrade. This would not be easy if you install services directly.

It would be a huge refactor, and I think it would be a regression with many disadvantages!

**Comment by nimagp** [comment]
> Hi,
> 
> Thank you for your kind words and feedback.
> 
> One of the design goals of this script is to make as few changes as possible to the OS by using containers and Docker. I can say that this script has the lowest resource footprint compared to other methods that use a GUI for management, by sacrificing a bit of overhead for Docker instead of GBs of RAM for a web interface.
> 
> This approach also enables us to make this script portable across different OSes. Additionally, you can copy the entire /opt/reality-ezpz directory to another server and run exactly the same configuration on other servers. This is helpful in case you want to migrate to a new server if the IP is blacklisted.
> 
> If you look at the code of the Telegram bot, you will see that the bot also executes the entire script with each call. If you want to create an installer like other scripts that use the underlying OS, then you need to accommodate different OSes, and you cannot backup and migrate configurations easily.
> 
> I can provide an over-the-air update by changing the version of the Docker image in the script, and users might not even notice the upgrade. This would not be easy if you install services directly.
> 
> It would be a huge refactor, and I think it would be a regression with many disadvantages!

I see, thanks.
Should this issue be closed?
