### ISSUE TITLE
Port 80 already in use

### ISSUE THREAD

**Issue by RiskierSubset** [aleskxyz/reality-ezpz#172]
failed to bind port 0.0.0.0:80/tcp: Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use.

Is it possible to fix this?

**Comment by RiskierSubset** [comment]
I think it has to do with nginx also using port 80. But I'm using nextcloud on this server and unfortunately I need it to work. I will greatly appreciate if you could provide me a solution. Thank you.

**Comment by netrolite** [comment]
have you found any solution to this? I need to be able to access a web server over https on my VPS, which I also set up as a proxy server using this script.

The proxy service is running on ports 80 and 443 and I can't set up nginx to run on those ports because they're already taken...

And the letsencrypt documentation says port 80 needs to be available

**Comment by aleskxyz** [comment]
Letsencrypt must use port 80 to validate the hostname.
You need to update the configuration of other services to use ports other than 80
